//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DEV_CODES_APPDBEntities : DbContext
    {
        public DEV_CODES_APPDBEntities()
            : base("name=DEV_CODES_APPDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<L_Country> L_Country { get; set; }
        public virtual DbSet<L_County> L_County { get; set; }
        public virtual DbSet<L_State> L_State { get; set; }
        public virtual DbSet<temp_BPMData> temp_BPMData { get; set; }
    }
}
