//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_County
    {
        public string CountyID { get; set; }
        public string CountyName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string StateID { get; set; }
    
        public virtual L_State L_State { get; set; }
    }
}
