//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOSBPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_BPMData
    {
        public int id { get; set; }
        public string AppID { get; set; }
        public string UserID { get; set; }
        public string JsonData { get; set; }
    }
}
